"""
Hand-labeled training data for the complaint classification engine.

Each row is (complaint_text, category, priority). This is intentionally a
compact, broad-coverage dataset meant to demonstrate the TF-IDF +
Logistic Regression pipeline end-to-end. For production use, replace this
with real historical complaint data collected from the institution.
"""

TRAINING_DATA = [
    # ---------------- Infrastructure ----------------
    ("The restroom is not clean.", "Infrastructure", "Medium"),
    ("Toilets in the second floor washroom are dirty and smell bad.", "Infrastructure", "Medium"),
    ("The ceiling fan in classroom 204 is broken and not working.", "Infrastructure", "Medium"),
    ("There is no water supply in the boys washroom since morning.", "Infrastructure", "Medium"),
    ("The projector in the seminar hall is not functioning.", "Infrastructure", "Low"),
    ("Classroom benches are broken and uncomfortable to sit on.", "Infrastructure", "Low"),
    ("Air conditioning in the computer lab has stopped working.", "Infrastructure", "Medium"),
    ("Water is leaking from the roof in the corridor near block B.", "Infrastructure", "Medium"),
    ("Streetlights near the parking area are not working at night.", "Infrastructure", "Medium"),
    ("The lift in the academic block has been out of service for a week.", "Infrastructure", "Medium"),
    ("Drinking water cooler on the third floor is not working.", "Infrastructure", "Low"),
    ("The whiteboard markers and chalk are never restocked in our classroom.", "Infrastructure", "Low"),
    ("Door lock of the chemistry lab is broken.", "Infrastructure", "Low"),
    ("WiFi connectivity is extremely poor in the hostel rooms.", "Infrastructure", "Low"),
    ("The main gate's automatic door has been stuck for two days.", "Infrastructure", "Medium"),
    ("Plaster from the ceiling of the lecture hall is falling off.", "Infrastructure", "High"),
    ("Exposed electrical wiring near the staircase looks dangerous.", "Infrastructure", "High"),
    ("The football ground has large potholes causing injuries during practice.", "Infrastructure", "Medium"),
    ("Power sockets in the lab are loose and sparking occasionally.", "Infrastructure", "High"),
    ("The water cooler dispenses dirty brownish water.", "Infrastructure", "Medium"),

    # ---------------- Academic ----------------
    ("Our professor has not returned our mid-term exam papers yet.", "Academic", "Low"),
    ("The timetable for the elective course was never published.", "Academic", "Medium"),
    ("There is a clash between two compulsory subjects in our schedule.", "Academic", "Medium"),
    ("We have not received lecture notes for the last three classes.", "Academic", "Low"),
    ("The internal assessment marks were uploaded incorrectly on the portal.", "Academic", "Medium"),
    ("Our class has had no substitute teacher for two weeks after the professor resigned.", "Academic", "High"),
    ("The syllabus copy given to us does not match what is being taught.", "Academic", "Medium"),
    ("Lab sessions for this semester have not started even though it's week six.", "Academic", "Medium"),
    ("We were not informed about the change in exam date.", "Academic", "Medium"),
    ("The professor is constantly absent and classes are not being compensated.", "Academic", "High"),
    ("Grading of our assignment seems inconsistent and unfair.", "Academic", "Low"),
    ("Question paper had two questions outside the syllabus.", "Academic", "Medium"),
    ("We need extra revision classes before the final examination.", "Academic", "Low"),
    ("The attendance recorded on the portal does not match actual attendance.", "Academic", "Medium"),
    ("Our project guide has not responded to emails for a month.", "Academic", "Medium"),
    ("Practical exam schedule overlaps with another department's exam.", "Academic", "Medium"),
    ("Course material uploaded on the LMS is incomplete.", "Academic", "Low"),
    ("We did not receive credit for a workshop we attended.", "Academic", "Low"),
    ("Re-evaluation request for our answer sheet has not been processed.", "Academic", "Medium"),
    ("The faculty advisor never schedules mentoring sessions.", "Academic", "Low"),

    # ---------------- Safety ----------------
    ("There is smoke coming from the laboratory.", "Safety", "High"),
    ("A fire alarm went off in the hostel building and nobody responded.", "Safety", "High"),
    ("Gas leakage smell detected near the canteen kitchen.", "Safety", "High"),
    ("A senior student threatened a junior with physical violence.", "Safety", "High"),
    ("There was a small electrical fire in the server room.", "Safety", "High"),
    ("Stray dogs near the hostel gate have been attacking students.", "Safety", "High"),
    ("Fire extinguishers in the chemistry block are expired and unusable.", "Safety", "High"),
    ("Someone brought a knife onto campus and threatened classmates.", "Safety", "High"),
    ("The emergency exit door in the library is permanently locked.", "Safety", "High"),
    ("A live wire is hanging near the bus stop inside the campus.", "Safety", "High"),
    ("Students felt unsafe walking near the unlit parking lot at night.", "Safety", "Medium"),
    ("The security guard at the main gate was missing during late hours.", "Safety", "Medium"),
    ("Broken glass on the lab floor is a hazard for barefoot students.", "Safety", "Medium"),
    ("CCTV cameras near the girls hostel entrance are not working.", "Safety", "Medium"),
    ("Chemicals in the lab were left unlabeled and unsecured.", "Safety", "High"),
    ("There was a minor scuffle between two groups of students in the canteen.", "Safety", "Medium"),
    ("The boundary wall near the lake has collapsed, creating a fall risk.", "Safety", "High"),
    ("Smoke detectors in the hostel corridor have been disabled.", "Safety", "High"),
    ("A loose railing on the third floor staircase nearly caused a fall.", "Safety", "High"),
    ("Bikes are being driven recklessly inside the campus near the academic block.", "Safety", "Medium"),

    # ---------------- Hostel ----------------
    ("Hostel mess food quality has been very poor this week.", "Hostel", "Medium"),
    ("Our hostel room geyser has not been working for ten days.", "Hostel", "Medium"),
    ("There is a severe cockroach infestation in the hostel kitchen.", "Hostel", "Medium"),
    ("Hostel curfew rules are not being communicated clearly to new students.", "Hostel", "Low"),
    ("Washing machines in the hostel laundry room are all out of order.", "Hostel", "Low"),
    ("Hostel warden is unreachable for emergency requests at night.", "Hostel", "High"),
    ("Bedbugs have infested several rooms in the boys hostel.", "Hostel", "Medium"),
    ("Hostel mess bill was charged incorrectly for this month.", "Hostel", "Low"),
    ("There is no hot water in the girls hostel bathroom during winter.", "Hostel", "Medium"),
    ("Hostel room allotment was done unfairly favoring certain students.", "Hostel", "Medium"),
    ("The hostel common room TV and furniture have been broken for months.", "Hostel", "Low"),
    ("Drainage in the hostel bathroom is blocked causing flooding.", "Hostel", "Medium"),
    ("Hostel WiFi router has not worked since last week.", "Hostel", "Low"),
    ("Visitors are being let into the hostel without proper verification.", "Hostel", "High"),
    ("Hostel mess menu has not been changed in over two months.", "Hostel", "Low"),
    ("Power backup in the hostel fails every time there is a cut.", "Hostel", "Medium"),
    ("Hostel room was allotted with a broken window letting in rain.", "Hostel", "Medium"),
    ("Ragging-like behavior was reported by a first year student in the hostel.", "Hostel", "High"),
    ("Hostel mess hygiene during food preparation looked very unsafe.", "Hostel", "High"),
    ("Hostel late-night noise from a few rooms disturbs other students daily.", "Hostel", "Low"),

    # ---------------- Library ----------------
    ("The library does not have enough copies of the prescribed textbook.", "Library", "Low"),
    ("Library reading room AC has not worked for the past month.", "Library", "Low"),
    ("Library staff are rude when students ask for help finding books.", "Library", "Low"),
    ("Online journal access through the library portal keeps failing.", "Library", "Medium"),
    ("Library closes earlier than the posted timing every day.", "Library", "Low"),
    ("Noise levels in the library reading hall are too high to study.", "Library", "Low"),
    ("Several library computers are outdated and crash frequently.", "Library", "Low"),
    ("Library fine system charged us incorrectly for a returned book.", "Library", "Low"),
    ("New arrivals in the library are not catalogued for months.", "Library", "Low"),
    ("Library Wi-Fi disconnects every few minutes making research difficult.", "Library", "Medium"),
    ("Photocopy machine in the library is broken for the third time this semester.", "Library", "Low"),
    ("Library seating is insufficient during exam season.", "Library", "Medium"),
    ("Damaged book pages were never replaced despite multiple requests.", "Library", "Low"),
    ("The library database for research papers is not updated.", "Library", "Low"),
    ("Returning books online is not reflected in our library account.", "Library", "Medium"),

    # ---------------- Transport ----------------
    ("College bus number 4 has been arriving 40 minutes late every day.", "Transport", "Medium"),
    ("The college bus brakes felt faulty during this morning's ride.", "Transport", "High"),
    ("Bus driver was rash and overspeeding on the highway route.", "Transport", "High"),
    ("There aren't enough buses for the new route added this semester.", "Transport", "Medium"),
    ("Bus pass renewal process takes weeks with no updates.", "Transport", "Low"),
    ("The shuttle between hostel and campus stopped running this week.", "Transport", "Medium"),
    ("Bus seats are torn and uncomfortable for the long commute.", "Transport", "Low"),
    ("Overcrowding in the college bus is becoming a safety concern.", "Transport", "Medium"),
    ("Transport office is not responding to lost item complaints.", "Transport", "Low"),
    ("The bus AC has not worked for the entire summer.", "Transport", "Low"),
    ("A bus door would not close properly during the trip today.", "Transport", "High"),
    ("Transport fee was charged twice this semester by mistake.", "Transport", "Medium"),

    # ---------------- Administrative ----------------
    ("Our scholarship application has been pending for three months with no update.", "Administrative", "Medium"),
    ("The admin office gave conflicting information about the fee deadline.", "Administrative", "Medium"),
    ("ID card replacement request has not been processed for weeks.", "Administrative", "Low"),
    ("Transcript request submitted last month has still not been issued.", "Administrative", "Medium"),
    ("Refund for the cancelled workshop has not been credited yet.", "Administrative", "Medium"),
    ("The fee receipt generated has incorrect details on it.", "Administrative", "Low"),
    ("Admin staff were unhelpful and dismissive when we asked about bonafide certificates.", "Administrative", "Low"),
    ("Online portal for fee payment crashes every time we try to pay.", "Administrative", "Medium"),
    ("Our migration certificate request has been delayed without explanation.", "Administrative", "Medium"),
    ("The notice board is never updated with current circulars.", "Administrative", "Low"),
    ("We were charged a late fee despite paying within the deadline.", "Administrative", "Medium"),
    ("Admission related documents submitted were lost by the office.", "Administrative", "High"),
    ("The helpdesk takes days to respond to simple email queries.", "Administrative", "Low"),
    ("Caste certificate verification has been stuck in admin for two months.", "Administrative", "Medium"),

    # ---------------- Ragging & Harassment ----------------
    ("A group of seniors have been bullying first year students in the hostel.", "Ragging & Harassment", "High"),
    ("I am being harassed online by a classmate through social media.", "Ragging & Harassment", "High"),
    ("A faculty member made inappropriate comments about a student's appearance.", "Ragging & Harassment", "High"),
    ("New students are being forced to do humiliating tasks by seniors.", "Ragging & Harassment", "High"),
    ("A student is being stalked by another student on campus.", "Ragging & Harassment", "High"),
    ("Discriminatory remarks were made against students from a particular region.", "Ragging & Harassment", "High"),
    ("Anonymous threatening messages were sent to a student's phone.", "Ragging & Harassment", "High"),
    ("Seniors forced juniors to skip meals as part of an initiation ritual.", "Ragging & Harassment", "High"),
    ("A staff member is repeatedly making students uncomfortable with personal questions.", "Ragging & Harassment", "High"),
    ("Verbal abuse and name-calling have become common in our class group chat.", "Ragging & Harassment", "Medium"),

    # ---------------- Other ----------------
    ("The cafeteria does not offer any vegetarian options on some days.", "Other", "Low"),
    ("Our student club's fund request has not been approved this year.", "Other", "Low"),
    ("Parking space allotted for students is often taken over by staff vehicles.", "Other", "Low"),
    ("The college app crashes frequently when checking the timetable.", "Other", "Low"),
    ("Vending machines on campus have been empty for weeks.", "Other", "Low"),
    ("We were not informed about a change of venue for the cultural fest.", "Other", "Low"),
    ("The sports committee has not responded to our equipment request.", "Other", "Low"),
    ("Our event proposal for the tech fest was rejected without feedback.", "Other", "Low"),
]
